add wave -position insertpoint  \
sim:/tb_vortex_axi/decode/AXI_DATA_WIDTH \
sim:/tb_vortex_axi/decode/AXI_ADDR_WIDTH \
sim:/tb_vortex_axi/decode/AXI_TID_WIDTH \
sim:/tb_vortex_axi/decode/AXI_NUM_BANKS \
sim:/tb_vortex_axi/decode/VIRTUAL_ADDR_WIDTH \
sim:/tb_vortex_axi/decode/PHYSICAL_ADDR_WIDTH \
sim:/tb_vortex_axi/decode/ADDR \
sim:/tb_vortex_axi/decode/clk \
sim:/tb_vortex_axi/decode/reset \
sim:/tb_vortex_axi/decode/m_axi_arvalid \
sim:/tb_vortex_axi/decode/m_axi_rready \
sim:/tb_vortex_axi/decode/m_axi_awaddr \
sim:/tb_vortex_axi/decode/m_axi_araddr \
sim:/tb_vortex_axi/decode/m_axi_awvalid \
sim:/tb_vortex_axi/decode/m_axi_wvalid \
sim:/tb_vortex_axi/decode/m_axi_wdata \
sim:/tb_vortex_axi/decode/m_axi_awburst \
sim:/tb_vortex_axi/decode/m_axi_awsize \
sim:/tb_vortex_axi/decode/m_axi_awlen \
sim:/tb_vortex_axi/decode/m_axi_awid \
sim:/tb_vortex_axi/decode/m_axi_wstrb \
sim:/tb_vortex_axi/decode/m_axi_awprot \
sim:/tb_vortex_axi/decode/m_axi_arsize \
sim:/tb_vortex_axi/decode/m_axi_awcache \
sim:/tb_vortex_axi/decode/m_axi_awlock \
sim:/tb_vortex_axi/decode/m_axi_bready \
sim:/tb_vortex_axi/decode/m_axi_wlast \
sim:/tb_vortex_axi/decode/m_axi_arcache \
sim:/tb_vortex_axi/decode/m_axi_arprot \
sim:/tb_vortex_axi/decode/m_axi_arlock \
sim:/tb_vortex_axi/decode/m_axi_arburst \
sim:/tb_vortex_axi/decode/m_axi_arlen \
sim:/tb_vortex_axi/decode/m_axi_arid \
sim:/tb_vortex_axi/decode/m_axi_rvalid \
sim:/tb_vortex_axi/decode/m_axi_bresp \
sim:/tb_vortex_axi/decode/m_axi_rdata \
sim:/tb_vortex_axi/decode/m_axi_arready \
sim:/tb_vortex_axi/decode/m_axi_bid \
sim:/tb_vortex_axi/decode/m_axi_bvalid \
sim:/tb_vortex_axi/decode/m_axi_wready \
sim:/tb_vortex_axi/decode/m_axi_awready \
sim:/tb_vortex_axi/decode/m_axi_rlast \
sim:/tb_vortex_axi/decode/m_axi_rid \
sim:/tb_vortex_axi/decode/m_axi_rresp \
sim:/tb_vortex_axi/decode/packed_bvalid0 \
sim:/tb_vortex_axi/decode/packed_wready0 \
sim:/tb_vortex_axi/decode/packed_rlast0 \
sim:/tb_vortex_axi/decode/packed_bid0 \
sim:/tb_vortex_axi/decode/packed_arready0 \
sim:/tb_vortex_axi/decode/packed_rvalid0 \
sim:/tb_vortex_axi/decode/packed_rdata0 \
sim:/tb_vortex_axi/decode/packed_awready0 \
sim:/tb_vortex_axi/decode/packed_bresp0 \
sim:/tb_vortex_axi/decode/packed_arprot0 \
sim:/tb_vortex_axi/decode/packed_rid0 \
sim:/tb_vortex_axi/decode/packed_rresp0 \
sim:/tb_vortex_axi/decode/packed_bvalid1 \
sim:/tb_vortex_axi/decode/packed_wready1 \
sim:/tb_vortex_axi/decode/packed_rlast1 \
sim:/tb_vortex_axi/decode/packed_bid1 \
sim:/tb_vortex_axi/decode/packed_arready1 \
sim:/tb_vortex_axi/decode/packed_rvalid1 \
sim:/tb_vortex_axi/decode/packed_rdata1 \
sim:/tb_vortex_axi/decode/packed_awready1 \
sim:/tb_vortex_axi/decode/packed_bresp1 \
sim:/tb_vortex_axi/decode/packed_arprot1 \
sim:/tb_vortex_axi/decode/packed_rid1 \
sim:/tb_vortex_axi/decode/packed_rresp1 \
sim:/tb_vortex_axi/decode/m_axi_arvalid_d \
sim:/tb_vortex_axi/decode/m_axi_rready_d \
sim:/tb_vortex_axi/decode/m_axi_awaddr_d \
sim:/tb_vortex_axi/decode/m_axi_araddr_d \
sim:/tb_vortex_axi/decode/m_axi_awvalid_d \
sim:/tb_vortex_axi/decode/m_axi_wvalid_d \
sim:/tb_vortex_axi/decode/m_axi_wdata_d \
sim:/tb_vortex_axi/decode/m_axi_rresp_d \
sim:/tb_vortex_axi/decode/m_axi_awid_d \
sim:/tb_vortex_axi/decode/m_axi_wstrb_d \
sim:/tb_vortex_axi/decode/m_axi_bready_d \
sim:/tb_vortex_axi/decode/m_axi_wlast_d \
sim:/tb_vortex_axi/decode/m_axi_rid_d \
sim:/tb_vortex_axi/decode/m_axi_arvalid_d1 \
sim:/tb_vortex_axi/decode/m_axi_rready_d1 \
sim:/tb_vortex_axi/decode/m_axi_awaddr_d1 \
sim:/tb_vortex_axi/decode/m_axi_araddr_d1 \
sim:/tb_vortex_axi/decode/m_axi_awvalid_d1 \
sim:/tb_vortex_axi/decode/m_axi_wvalid_d1 \
sim:/tb_vortex_axi/decode/m_axi_wdata_d1 \
sim:/tb_vortex_axi/decode/m_axi_rresp_d1 \
sim:/tb_vortex_axi/decode/m_axi_awid_d1 \
sim:/tb_vortex_axi/decode/m_axi_wstrb_d1 \
sim:/tb_vortex_axi/decode/m_axi_bready_d1 \
sim:/tb_vortex_axi/decode/m_axi_wlast_d1 \
sim:/tb_vortex_axi/decode/m_axi_rid_d1 \
sim:/tb_vortex_axi/decode/from_r1 \
sim:/tb_vortex_axi/decode/to_r1 \
sim:/tb_vortex_axi/decode/from_r2 \
sim:/tb_vortex_axi/decode/to_r2 \
sim:/tb_vortex_axi/decode/m_axi_arlen_d1 \
sim:/tb_vortex_axi/decode/m_axi_awlen_d1 \
sim:/tb_vortex_axi/decode/m_axi_awsize_d1 \
sim:/tb_vortex_axi/decode/m_axi_awburst_d1 \ 
sim:/tb_vortex_axi/vortex/vortex/mem_req_valid \
sim:/tb_vortex_axi/vortex/vortex/mem_req_rw \
sim:/tb_vortex_axi/vortex/vortex/mem_req_byteen \
sim:/tb_vortex_axi/vortex/vortex/mem_req_addr \
sim:/tb_vortex_axi/vortex/vortex/mem_req_data \
sim:/tb_vortex_axi/vortex/vortex/mem_req_tag \
sim:/tb_vortex_axi/vortex/vortex/mem_req_ready \
sim:/tb_vortex_axi/vortex/vortex/mem_rsp_valid \
sim:/tb_vortex_axi/vortex/vortex/mem_rsp_data \
sim:/tb_vortex_axi/vortex/vortex/mem_rsp_tag \
sim:/tb_vortex_axi/vortex/vortex/mem_rsp_ready \
{sim:/tb_vortex_axi/vortex/vortex/per_cluster_mem_bus_if[0]/req_valid} \
{sim:/tb_vortex_axi/vortex/vortex/per_cluster_mem_bus_if[0]/req_data} \
{sim:/tb_vortex_axi/vortex/vortex/per_cluster_mem_bus_if[0]/req_ready} \
{sim:/tb_vortex_axi/vortex/vortex/per_cluster_mem_bus_if[0]/rsp_valid} \
{sim:/tb_vortex_axi/vortex/vortex/per_cluster_mem_bus_if[0]/rsp_data} \
{sim:/tb_vortex_axi/vortex/vortex/per_cluster_mem_bus_if[0]/rsp_data.data} \
{sim:/tb_vortex_axi/vortex/vortex/per_cluster_mem_bus_if[0]/rsp_data.tag} \
{sim:/tb_vortex_axi/vortex/vortex/per_cluster_mem_bus_if[0]/rsp_ready} 

add wave -position insertpoint  \
sim:/tb_vortex_axi/vortex/busy

#add wave -position insertpoint sim:/tb_vortex_axi/decode/ram1/*
#add wave -position insertpoint sim:/tb_vortex_axi/decode/ram0/*